app:
  name: idist-blog
  env: development
  debug: true
  secret:
    jwt: aCSnbH6B1ATyRIDkOS3pB9xXMwOza9m7XrPnceNNVXxwvkbqjXwqgTuFgD1j6GsA
  server:
    host: 0.0.0.0
    port: 6006
    log: true
    domain: http://cms.test
    media: http://cms.test
    version: 2024.09.05.06.18
    branch: refactoring[0d80d1d399f2316b5f83fa20a1375078829642e5]
  frontend:
    enable: true
    environment: development
role:
  admin_id: 6180f9624652255c7f18c206
