app:
  name: idist-blog
  env: development
  debug: true
  secret:
    jwt: aCSnbH6B1ATyRIDkOS3pB9xXMwOza9m7XrPnceNNVXxwvkbqjXwqgTuFgD1j6GsA
  server:
    host: 0.0.0.0
    port: 6006
    log: true
    domain: http://cms.test
    media: http://cms.test
    version: 2024.08.07.17.05
    branch: refactoring[939e8f7c4757feba8141c683a26ea611dc0aea5d]
  frontend:
    enable: true
    environment: development
role:
  admin_id: 6180f9624652255c7f18c206
